const INTERNAL_METADATA = {
  PROTECTED_ROUTES: 'PROTECTED_ROUTES',
  SITE_PASSWORD: 'SITE_PASSWORD',
  CLOSED_ROUTES: 'CLOSED_ROUTES',
  ROUTE_METADATA: 'ROUTE_METADATA',
} as const;

const INTERNAL_SITES = {
  ADMIN: '/admin',
  PASSWORD_PROTECTOR: '/password-protector',
} as const;

export { INTERNAL_METADATA, INTERNAL_SITES };